Issue 2
bmaparpaing/compliqom pull request #10
Opened 2022-09-24 11:04 UTC by scaunois

2022-09-25 19:21 UTC, bmaparpaing requested changes

2022-09-25 19:21 UTC, bmaparpaing commented on src/App.vue
> + * Vérifie la validité du mot tapé par le joueur. Si le mot est valide, passe à la ligne suivante, sinon annule le coup (efface le mot) et affiche un message d'erreur
Garde juste la première phrase, vu que la méthode ne s'occupe absolument pas de ce que tu as décrit en deuxième phrase. Tu peux déplacer la deuxième phrase dans un commentaire plus haut, genre ligne ~29

2022-09-25 19:21 UTC, bmaparpaing commented on src/App.vue
> +.invalid-word {
Il faudrait lui mettre un font-family parce qu'en l'état le message pique les yeux. Remonte/Copie la définition de font-family de GameCell dans ce composant, ou peut-être ajoute-le carrément dans le main.css sur le body.

2022-09-25 19:21 UTC, bmaparpaing commented on src/App.vue
> +    color: darkorange;
Avec une couleur un peu plus clair peut-être ? :smile: "orange" est déjà moins agressif.

2022-09-25 19:43 UTC, bmaparpaing commented on src/dictionary-service.ts
> +    private static allowedWords: string[] = []; // la liste des mots autorisés pour la saisie par le joueur
Ça va pas passer avec le TU que tu as fait dans la prochaine PR.

2022-09-25 20:23 UTC, scaunois commented on src/App.vue
> + * Vérifie la validité du mot tapé par le joueur. Si le mot est valide, passe à la ligne suivante, sinon annule le coup (efface le mot) et affiche un message d'erreur
bien vu, c'est corrigé 👍

2022-09-25 20:31 UTC, scaunois commented on src/dictionary-service.ts
> +    private static allowedWords: string[] = []; // la liste des mots autorisés pour la saisie par le joueur
Alors, en fait, je l'aurais supprimé lors du rebase. Mais je vais le supprimer dès maintenant, ça évitera de polluer avec des modifs inutiles.
Je préfèrerais garder la variable en private, mais je sais pas trop comment m'y prendre pour le TU par la suite, car j'ai besoin de set cette variable. Je pense que c'est pas possible de la mocker, donc sinon il faudrait la mettre private et créer un setter juste pour le besoin du TU... C'est une bonne pratique de l'avoir en private mais ça me bloque pour mon test pour l'instant, donc je la remet en public et on verra plus tard si on peut la rendre private sans bloquer le TU.

2022-09-25 20:50 UTC, scaunois commented on src/App.vue
> +.invalid-word {
j'ai mis la même police, déplacée dans main.css.

2022-09-25 20:51 UTC, scaunois commented on src/App.vue
> +    color: darkorange;
j'ai remis en blanc.

2022-09-26 16:26 UTC, bmaparpaing approved these changes

2022-09-26 16:26 UTC, merged