✨ #4 - Gérer la fin de partie
bmaparpaing/compliqom pull request #15
Opened 2022-09-28 22:02 UTC by scaunois

Closes #4

2022-09-29 16:40 UTC, bmaparpaing requested changes

2022-09-29 16:40 UTC, bmaparpaing commented on src/App.vue
> +    if (word === solution) {
Il faudrait mettre la suite du bloc dans un else (à partir de `checkWordValidity(word);`) car sinon on va ajouter des `.` sur la ligne suivante. C'est pas très gênant mais s'arrêter à la ligne qui gagne, ça fera plus propre.

2022-09-29 16:56 UTC, scaunois commented on src/App.vue
> +    if (word === solution) {
ça marche, effectivement, j'avais vu que ça faisait comme tu décris mais je savais pas si c'était le comportement que tu souhaitais ou pas donc j'avais laissé 😉
Je vais corriger.

2022-09-30 16:58 UTC, bmaparpaing requested changes

2022-09-30 16:58 UTC, bmaparpaing commented on src/App.vue
> +    if (word === solution) {
Il faut que le giveHint() passe avant pour qu'on affiche toutes les cases en rouge + le message de succès. Donc dans l'ordre :
1. vérifier la validité du mot
2. Si ok, donner les indices puis vérifier si c'est la solution
3. Si == solution, gagner et stop
4. Si pas solution, passer à la ligne suivante ou perdre

2022-10-01 09:21 UTC, scaunois commented on src/App.vue
> +    if (word === solution) {
Done !

2022-10-01 13:16 UTC, merged

2022-10-01 13:16 UTC, bmaparpaing approved these changes